## 一.ndarray的特性
### 1.多维性

In [2]:
import numpy as np
from numpy.matlib import randn

arr0 = np.array(0)
print(arr0)
print("arr的维度为：", arr0.ndim) #number of dimensions

0
arr的维度为： 0


In [3]:
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)
print("arr1的维度为：", arr1.ndim)

[1 2 3 4 5]
arr的维度为： 1


In [4]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)
print("arr2的维度为：", arr2.ndim)

[[1 2 3]
 [4 5 6]]
arr2的维度为： 2


### 2.同质性

In [7]:
arr0 = np.array([1,"Hello"])
arr1 = np.array([1,2.5])
print(arr0) #不同数据数据类型会被强制转换为相同类型
print(arr1) #升维转换

['1' 'Hello']
[1.  2.5]


## 二.ndarray的属性

In [14]:
arr0 = np.array(1)
print("arr0数组的形状为：", arr0.shape)
print("arr0数组的维度为：",arr0.ndim)
print("arr0数组的元素个数为：", arr0.size)
print("arr0数组的数据类型为：", arr0.dtype)

arr0数组的形状为： ()
arr0数组的维度为： 0
arr0数组的元素个数为： 1
arr0数组的数据类型为： int64


In [15]:
arr1 = np.array([1, 2, 3])
print("arr1数组的形状为：", arr1.shape)
print("arr1数组的维度为：",arr1.ndim)
print("arr1数组的元素个数为：", arr1.size)
print("arr1数组的数据类型为：", arr1.dtype)

arr1数组的形状为： (3,)
arr1数组的维度为： 1
arr1数组的元素个数为： 3
arr1数组的数据类型为： int64


In [16]:
arr2 = np.array([[1, 2, 3],[4, 5, 6]])
print("arr2数组的形状为：", arr2.shape)
print("arr2数组的维度为：",arr2.ndim)
print("arr2数组的元素个数为：", arr2.size)
print("arr2数组的数据类型为：", arr2.dtype)

arr2数组的形状为： (2, 3)
arr2数组的维度为： 2
arr2数组的元素个数为： 6
arr2数组的数据类型为： int64


## 三.ndarray的创建

In [18]:
# 基础创建方法
arr = np.array([1, 2, 3],dtype=np.float64) #可以指定类型
print(arr)

[1. 2. 3.]


In [19]:
# copy
arr1 = np.copy(arr)
print(arr1)

[1. 2. 3.]


In [45]:
# 预定义形状的
# 全0
arr0 = np.zeros((2, 3))
print(arr0)
print(arr0.dtype)

[[0. 0. 0.]
 [0. 0. 0.]]
float64


In [46]:
# 全1
arr1 = np.ones((2, 3))
print(arr1)

[[1. 1. 1.]
 [1. 1. 1.]]


In [47]:
# 未初始化
arr2 = np.empty((2, 3))
print(arr2)

[[1. 1. 1.]
 [1. 1. 1.]]


In [48]:
# 填充
arr3 = np.full((2, 3), 5)
print(arr3)

[[5 5 5]
 [5 5 5]]


In [49]:
# 预定义形状,like谁就是谁的形状
arr4 = np.zeros_like(arr3)
print(arr4)
arr5 = np.ones_like(arr3)
print(arr5)
arr6 = np.empty_like(arr3)
print(arr6)
arr7 = np.full_like(arr3, 2025)
print(arr7)

[[0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]]
[[4607182418800017408 4607182418800017408 4607182418800017408]
 [4607182418800017408 4607182418800017408 4607182418800017408]]
[[2025 2025 2025]
 [2025 2025 2025]]


In [4]:
# 等差数列
arr = np.arange(1, 10, 2) #start, stop, step
print(arr)

[1 3 5 7 9]


In [6]:
# 等间隔的数列
arr = np.linspace(1, 10, 5) #把1到10等分为5份
print(arr)

[ 1.    3.25  5.5   7.75 10.  ]


In [8]:
# 指对数间隔数列
arr = np.logspace(0, 4, 3, base=2) #创建等比数列（对数刻度）的数组
"这里先将0-4分成3份，即linspace的用法，之后将其中的每一个都按base的幂打印出来"
print(arr)

[ 1.  4. 16.]


In [15]:
arr = np.logspace(0,4,3,base=3)
print(arr)

[ 1.  9. 81.]


In [21]:
# 特殊矩阵的构造
#单位矩阵：主对角线上的数字为1，其他为0
arr = np.eye(3,dtype=int)
print(arr)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [23]:
#对角矩阵：矩阵的元素全部为0，主对角线上的元素为非零
arr = np.diag([1,2,3,4])
print(arr)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [32]:
#随机数组的生成
arr = np.random.rand(2,3) #默认0-1间的随机浮点数
print(arr)
arr = np.random.uniform(1,10,(2,3)) #指定范围的指定形状的随机浮点数
print(arr)
arr = np.random.randint(1,10,(2,3)) #指定范围的指定形状的随机整数
print(arr)

[[0.11581236 0.57824211 0.18753199]
 [0.38768878 0.34761466 0.03140773]]
[[8.47918037 9.57978514 3.49462169]
 [2.63513419 4.07071549 2.39733427]]
[[6 7 5]
 [4 2 7]]


In [34]:
# 生成随机数列（正态分布）,默认标准正态分布，均值为0，方差为1
arr = np.random.randn(2,3)
print(arr)

[[ 1.34552837  1.83312409  0.11193052]
 [ 0.29362343 -1.06220854  1.88564043]]


In [41]:
# 设置随机种子
np.random.seed(20)
arr = np.random.randint(1,10,(2,3))
print(arr)

[[4 5 7]
 [8 3 1]]


## 四.ndarray的数据类型

In [46]:
# 布尔类型
arr = np.array([1, 0, 1, 1, 0, 0], dtype=bool)
print(arr)
# 整数类型
arr = np.array([1, 2, 127], dtype=np.int8) #当大于等于128时，会超范围
print(arr)

[ True False  True  True False False]
[  1   2 127]


## 五.索引和切片

In [53]:
# 一维数组的
arr = np.random.randint(1,100,20)
print(arr)
print(arr[0]) #索引
print(arr[1:5]) #切片
print(arr[(arr > 2) & (arr < 20)]) #布尔筛选

[16 66 31 89 50 41 12 70  1 59 87 38 69 19 10 58 15 36 76 24]
16
[66 31 89 50]
[16 12 19 10 15]


In [59]:
# 二维数组的
arr = np.random.randint(1,100,(4,8))
print(arr)
print(arr[1,1]) #索引
print(arr[1,2:4]) #切片
print(arr[2][arr[2] > 50])

[[34 22 69  7 19 33 25 21]
 [ 9 73 50 63 30 76 84 17]
 [55 54 74 83 67 31 55 66]
 [45 96 44 59 36 41 22  1]]
73
[50 63]
[55 54 74 83 67 55 66]


## 六.数组的运算

In [3]:
# 多维的亦没有问题
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(arr1 + arr2)
print(arr1 * arr2)
print(arr1 - arr2)
print(arr1 / arr2)

[5 7 9]
[ 4 10 18]
[-3 -3 -3]
[0.25 0.4  0.5 ]


In [5]:
# 广播机制；是否可以广播看同一维度：相同，1即可广播
a = np.array([1,2,3]) #1*3
b = np.array([[4],[5],[6]]) #3*1
"a"
"1 2 3"
"1 2 3"
"1 2 3"
"b"
"4 4 4"
"5 5 5"
"6 6 6"
print(a + b)

[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [10]:
# 矩阵的运算
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[4,5,6],[7,8,9],[1,2,3]])
print(a * b) #普通乘法
print(a @ b) #矩阵乘法
("普通乘法对应位置相乘即可"
 "矩阵乘法求[n,m]即a矩阵第n行所有数与b矩阵第m列所有数相乘再相加的结果"
 "如[0,0]:1*4+2*7+3*1=21")

[[ 4 10 18]
 [28 40 54]
 [ 7 16 27]]
[[ 21  27  33]
 [ 57  72  87]
 [ 93 117 141]]


'普通乘法对应位置相乘即可矩阵乘法求[n,m]即a矩阵第n行所有数与b矩阵第m列所有数相乘再相加的结果'

## 七.函数的运用
### 1.基本数学函数

In [12]:
# 计算平方根
print(np.sqrt(16))
print(np.sqrt([16, 25, 36]))

4.0
[4. 5. 6.]


In [14]:
# 计算指数
print(np.exp(1)) #计算e^x

2.718281828459045


In [18]:
# 计算自然对数
print(np.log(2.718281828459045)) #计算ln(x)

1.0


In [22]:
# 计算正余弦值
print(np.sin(1))
print(np.cos(1))
print(np.tan(1))
print(np.arcsin(1))
print(np.arccos(1))
print(np.arctan(1))
print(np.cos(np.pi))

0.8414709848078965
0.5403023058681398
1.5574077246549023
1.5707963267948966
0.0
0.7853981633974483
-1.0


In [24]:
# 计算绝对值
arr = np.array([-1, -2, 3, 4])
print(np.abs(arr))

[1 2 3 4]


In [26]:
# 幂运算
print(np.power(2, 3))

8


In [32]:
# 四舍五入
print(np.round(3.1415926, 2))
# 向上取整与向下取整
print(np.ceil(3.1)) #向上取整,ceil天花板
print(np.floor(3.1)) #向下取整,floor地板

3.14
4.0
3.0


In [34]:
# 检测缺失值
np.isnan([1,2,3,np.nan])

array([False, False, False,  True])

### 2.统计函数

In [51]:
arr = np.random.randint(1,20,8)
print(arr)
# 求和
print(np.sum(arr))
# 求均值
print(np.mean(arr))
# 求中位数
print(np.median(arr)) #总数奇数，值为中值；数总数偶数，值为中间两数均值

[19 16 15 19  9 15 10  3]
106
13.25
15.0


In [53]:
# 求方差
"1.先求均值=2"
"2.每个数减均值平方求和/个数：((1-2)^2+(2-2)^2+(3-2)^2) / 3 = 0.66"
print(np.var([1,2,3]))
# 求标准差
"1.先求方差,再多方差开根"
print(np.std([1,2,3]))

0.6666666666666666
0.816496580927726


In [57]:
print(arr)
# 最大值
print(np.max(arr),np.argmax(arr)) #后面可以获取最大值的索引
# 最小值
print(np.min(arr),np.argmin(arr))

[19 16 15 19  9 15 10  3]
19 0
3 7


In [64]:
np.random.seed(0)
arr = np.random.randint(1,100,4)
print(arr)
# 分位数
print(np.percentile(arr, 25)) #25%位置的数
"计算过程：总数个数*x%=y , 查原来的数第y和y+1的均值"

[45 48 65 68]
47.25


'计算过程：总数个数*x%=y , 查原来的数第y和y+1的均值'

In [66]:
# 累积和、累积积
arr = np.array([1,2,3])
print(np.sum(arr))
print(np.cumsum(arr)) #累积和，[1, 1+2 , 1+2+3]
print(np.cumprod(arr)) #累积积，[1, 1*2 , 1*2*3]

6
[1 3 6]
[1 2 6]


### 3.比较函数

In [69]:
# 是否大于
print(np.greater([1,2,3,4,5,6],4))
# 是否小于
print(np.less([1,2,3,4,5,6],4))
# 是否等于
print(np.equal([1,2,3,4,5,6],4))

[False False False False  True  True]
[ True  True  True False False False]
[False False False  True False False]


In [79]:
# 逻辑运算：与、或、非
print(np.logical_and([1,0],[1,1]))
print(np.logical_or([1,0],[1,1]))
print(np.logical_not([1,0]))
# 检查元素是否至少有一个为True
print(np.any([1,0]))
# 检查元素是否全部为True
print(np.all([1,0]))
# 自定义条件
arr = np.array([1,2,3,4,5,6])
print(np.where(arr>3,arr,-1))
# 多条件
arr = np.random.randint(1,100,20)
print(arr)
print(np.select([arr<60,(arr>=60) & (arr<=80),arr>80],["bad","good","excellent"],default="NAN"))


[ True False]
[ True  True]
[False  True]
True
False
[-1 -1 -1  4  5  6]
[48  4 77 53 79 16 21 59 24 80 14 86 49 50 70 42 36 65 96 70]
['bad' 'bad' 'good' 'bad' 'good' 'bad' 'bad' 'bad' 'bad' 'good' 'bad'
 'excellent' 'bad' 'bad' 'good' 'bad' 'bad' 'good' 'excellent' 'good']


### 4.排序函数

In [84]:
np.random.seed(0)
arr = np.random.randint(1,100,20)
print(arr)
print(np.sort(arr)) #默认升序,不会修改原数组
#arr.sort() #升序,会修改原数组
print(arr)
print(np.argsort(arr)) #获取排序后的索引

[45 48 65 68 68 10 84 22 37 88 71 89 89 13 59 66 40 88 47 89]
[10 13 22 37 40 45 47 48 59 65 66 68 68 71 84 88 88 89 89 89]
[45 48 65 68 68 10 84 22 37 88 71 89 89 13 59 66 40 88 47 89]
[ 5 13  7  8 16  0 18  1 14  2 15  3  4 10  6  9 17 11 12 19]


### 5.去重函数

In [86]:
np.random.seed(0)
arr = np.random.randint(1,100,20)
print(arr)
print(np.unique(arr))

[45 48 65 68 68 10 84 22 37 88 71 89 89 13 59 66 40 88 47 89]
[10 13 22 37 40 45 47 48 59 65 66 68 71 84 88 89]


### 6.其他函数

In [87]:
# 拼接数组
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(np.concatenate([arr1,arr2]))

[1 2 3 4 5 6]


In [89]:
# 数组的分隔
np.random.seed(0)
arr = np.random.randint(1,100,20)
print(arr)
print(np.split(arr,5))
print(np.split(arr,[6,12,18])) #按索引位置切割

[45 48 65 68 68 10 84 22 37 88 71 89 89 13 59 66 40 88 47 89]
[array([45, 48, 65, 68], dtype=int32), array([68, 10, 84, 22], dtype=int32), array([37, 88, 71, 89], dtype=int32), array([89, 13, 59, 66], dtype=int32), array([40, 88, 47, 89], dtype=int32)]
[array([45, 48, 65, 68, 68, 10], dtype=int32), array([84, 22, 37, 88, 71, 89], dtype=int32), array([89, 13, 59, 66, 40, 88], dtype=int32), array([47, 89], dtype=int32)]


In [91]:
# 调整数组的形状
print(arr)
print(np.reshape(arr,[5,4]))

[45 48 65 68 68 10 84 22 37 88 71 89 89 13 59 66 40 88 47 89]
[[45 48 65 68]
 [68 10 84 22]
 [37 88 71 89]
 [89 13 59 66]
 [40 88 47 89]]


## 八.章节练习

In [ ]:
"""
题目1：温度数据分析
某城市一周的最高气温（°℃）为[28，30，29，31，32，30，29]。
计算平均气温、最高气温和最低气温。
找出气温超过30℃的天数。
"""

In [97]:
import numpy as np
arr = np.array([28,30,29,31,32,30,29])
print(round(np.mean(arr),2))
print(np.max(arr))
print(np.min(arr))
print(np.sum(arr>30))

29.86
32
28
2


In [ ]:
"""
题目2：学生成绩统计
某班级及5名学生的数学成绩为[85， 90， 78， 92， 88]。
计算成绩的平均分、中位数和标准差。
将成绩转换为十分制（假设满分为10)
"""

In [99]:
arr = np.array([85, 90, 78, 92, 88])
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.round(arr/10,2))

86.6
88.0
4.882622246293481
[8.5 9.  7.8 9.2 8.8]


In [ ]:
"""
题目3：矩阵运算
给定矩阵 A=[[1，2]，[3，4]] 和 B=[[5，6]，[7，8]]。
计算A+B和A＊B（逐元素乘法)
计算A 和B的矩阵乘法 (点积）
"""

In [100]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(a+b)
print(a*b)
print(a @ b)

[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]


In [ ]:
"""
题目4：随机数据生成
生成一个（3，4)的随机整数数组，范围[0, 10).
计算每列的最大值和每行的最小值。
将数组中的所有奇数替换为-1。
"""

In [111]:
np.random.seed(0)
arr = np.random.randint(0,10,(3,4))
print(arr)
print(np.max(arr,axis=0)) #axis=0列，axis=1行
print(np.min(arr,axis=1))
print(np.where(arr%2==1,-1,arr))

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]
[7 9 7 6]
[0 3 2]
[[-1  0 -1 -1]
 [-1 -1 -1 -1]
 [ 2  4 -1  6]]


In [ ]:
"""
题目5：数组变形
创建一个1到12的一维数组，并转换为（3，4）的二维数组。
计算每行的和与每列的平均值。
将数组展平为一维数组
"""

In [138]:
arr = np.arange(1,13)
print(arr)
print(arr.reshape(3,4))
print(np.sum(arr.reshape(3,4),axis=1))
print(np.mean(arr.reshape(3,4),axis=0))
print(arr.reshape(-1)) #-1表示自动计算维度

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[10 26 42]
[5. 6. 7. 8.]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
"""
生成一个（5，5)的随机数组，范围[0，20)。
找出数组中大于10的元素。
将所有大于10的元素替换为0
"""

In [141]:
np.random.seed(0)
arr = np.random.randint(0,20,(5,5))
print(arr)
print(arr[arr>10])
print(np.where(arr>10,0,arr))

[[12 15  0  3  3]
 [ 7  9 19 18  4]
 [ 6 12  1  6  7]
 [14 17  5 13  8]
 [ 9 19 16 19  5]]
[12 15 19 18 12 14 17 13 19 16 19]
[[0 0 0 3 3]
 [7 9 0 0 4]
 [6 0 1 6 7]
 [0 0 5 0 8]
 [9 0 0 0 5]]


In [ ]:
"""
题目7：统计函数应用
某公司6个月的销售额（万元）为［120，135，110，125，130，140］。
计算销售额的总和、均值和方差。
找出销售额最高的月份和最低的月份。
"""

In [143]:
arr = np.array([120,135,110,125,130,140])
print(np.sum(arr))
print(np.mean(arr))
print(np.var(arr))
print(np.argmax(arr) + 1)
print(np.argmin(arr) + 1)

760
126.66666666666667
97.22222222222223
6
3


In [ ]:
"""
题目8：数组拼接
给定A=[1， 2， 3] 和 B =[4， 5， 6]。
将将A和B水平拼接为一个新数组。
将A和B垂直拼接为一个新数组。
"""

In [146]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.concatenate([a,b]))
print(np.reshape(np.concatenate([a,b]),(2,3)))

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [ ]:
"""
题目9：唯一值与排序
给定数组[2， 1， 2, 3, 1， 4, 3]。
找出数组中的唯一值并排序，
计算每个唯一值出现的次数
"""

In [149]:
arr = np.array([2, 1, 2, 3, 1, 4, 3])
print(np.unique(arr))
u_arr,counts = np.unique(arr,return_counts=True)
print(u_arr,counts)

[1 2 3 4]
[1 2 3 4] [2 2 2 1]


In [ ]:
"""
题目20：综合应用
某商店5天的销售额(万元)和成本(万元)如下:
销售额：[20，25，22，30，28]
成本：[15，18，16，22，20]
计算每天的利润(销售额 － 成本)
计算利润的平均值和标准差。
找出利润最高的天数，
"""

In [157]:
a = np.array([20,25,22,30,28])
b = np.array([15,18,16,22,20])
print(a-b)
print(np.mean(a-b))
print(np.std(a-b))
print(len((a-b)[(a-b) == np.max(a-b)]))

[5 7 6 8 8]
6.8
1.16619037896906
2
